apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: notification-reminders-sub
spec:
  pubsubname: pubsub-kafka
  topic: reminders
  route: /events/reminder-due
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: notification-notifications-sub
spec:
  pubsubname: pubsub-kafka
  topic: notifications
  route: /events/notification
