apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub-kafka
  namespace: phase-v
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers
    value: "kafka.phase-v.svc.cluster.local:9092"
  - name: consumerID
    value: "{appID}"
  - name: authType
    value: "none"
  - name: initialOffset
    value: "newest"