{{- if .Values.global.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hack2-todo.secretName" . }}
  labels:
    {{- include "hack2-todo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.betterAuthSecret | quote }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
{{- end }}
