replicaCount: 1

image:
  repository: todo-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

dapr:
  enabled: true
  appId: backend
  appPort: 8000

env:
  DAPR_HTTP_PORT: "3500"
  PUBSUB_NAME: "pubsub-kafka"
  BETTER_AUTH_URL: "http://todo-frontend:3000"
  CORS_ORIGINS: "http://localhost:3000,http://todo-frontend:3000"

secrets:
  name: app-secrets

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
