replicaCount: 1

image:
  repository: todo-frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  NEXT_PUBLIC_API_URL: "http://localhost:8000"
  BETTER_AUTH_URL: "http://localhost:3000"
  NODE_ENV: "production"

secrets:
  name: app-secrets

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
